### ISSUE TITLE
Respect the formatting of the serializer when writing json for MultiPolygon 

### ISSUE THREAD

**Issue by russcam** [jbattermann/GeoJSON.Net#35]
The current implementation when writing the json for a MultiPolygon uses the default `.ToString()` method on a `JArray` which will write json with indented formatting. This causes problems in specific cases where the resulting json must have no formatting applied e.g. when using GeoJSON.NET in conjunction with Elasticsearch's [geo_shape type](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-shape-type.html), the Elasticsearch Bulk API uses newline (\n) characters to delimit the actions within the bulk request and the current formatting for a MultiPolygon causes exceptions similar to:

> Unexpected end-of-input: expected close marker for ARRAY (from [Source: [B@5ee6d620; line: 1, column: 2])
 at [Source: [B@5ee6d620; line: 2, column: 238]

I can send a pull request with a fix

**Comment by jbattermann** [comment]
@russcam thanks for reporting and yeah - a PR would be great!

**Comment by russcam** [comment]
PR sent!

**Comment by jbattermann** [comment]
Just pulled it in, thanks :+1:
